language: python
sudo: required
python:
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep python-pygame

install:
  - pip install -r requirements.txt
  - pip install cx_Freeze

script:
  - omnisetup.py build