items = {
    "Poisoned Knife": 250,
    "Diving Helmet": 1,
    "Goldfish": 99,
    "Staff of Regrowth": 1,
    "Flower of Fire": 1,
    "Anklet of the Wind": 1,
    "Silver Axe": 1,
    "Demon Bow": 1,
    "Meteor Hamaxe": 1,
    "Glowing Mushroom": 99,
    "Wooden Boomerang": 1,
    "Iron Greaves": 1,
    "Molten Fury": 1,
    "Gold Broadsword": 1,
    "Aqua Scepter": 1,
    "Molten Pickaxe": 1,
    "Restoration Potion": 20,
    "Gold Bow": 1,
    "Iron Pickaxe": 1,
    "Necro Helmet": 1,
    "Copper Helmet": 1,
    "Gold Shortsword": 1,
    "Enchanted Boomerang": 1,
    "Copper Watch": 1,
    "Thorn Chakram": 1,
    "Iron Hammer": 1,
    "Shadow Greaves": 1,
    "Necro Breastplate": 1,
    "Gold Chainmail": 1,
    "Yellow Phaseblade": 1,
    "Molten Greaves": 1,
    "Jungle Hat": 1,
    "Aglet": 1,
    "Silver Greaves": 1,
    "Silver Watch": 1,
    "Nature's Gift": 1,
    "Jungle Shirt": 1,
    "Shadow Scalemail": 1,
    "Red Phaseblade": 1,
    "Silver Bow": 1,
    "Copper Hammer": 1,
    "Flaming Arrow": 250,
    "Wooden Sword": 1,
    "Fiery Greatsword": 1,
    "Depth Meter": 1,
    "Jungle Pants": 1,
    "Hermes Boots": 1,
    "Rocket Boots": 1,
    "Cobalt Shield": 1,
    "Shiny Red Balloon": 1,
    "Silver Helmet": 1,
    "Gold Watch": 1,
    "Iron Bow": 1,
    "Iron Shortsword": 1,
    "Flipper": 1,
    "Dark Lance": 1,
    "Phoenix Blaster": 1,
    "Unholy Arrow": 250,
    "Spear": 1,
    "Gold Axe": 1,
    "Gold Pickaxe": 1,
    "Lesser Restoration Potion": 20,
    "Silver Broadsword": 1,
    "Minishark": 1,
    "Star Cannon": 1,
    "Green Phaseblade": 1,
    "Silver Pickaxe": 1,
    "Iron Helmet": 1,
    "Starfury": 1,
    "Mushroom": 99,
    "Gold Hammer": 1,
    "Purple Phaseblade": 1,
    "Bone": 99,
    "Meteor Helmet": 1,
    "Night's Edge": 1,
    "Nightmare Pickaxe": 1,
    "Ball O' Hurt": 1,
    "Mining Helmet": 1,
    "Lesser Healing Potion": 30,
    "Iron Chainmail": 1,
    "Copper Bow": 1,
    "Wooden Arrow": 250,
    "Meteor Leggings": 1,
    "White Phaseblade": 1,
    "Gold Greaves": 1,
    "Band of Regeneration": 1,
    "Copper Greaves": 1,
    "Necro Greaves": 1,
    "Silver Shortsword": 1,
    "Cloud in a Bottle": 1,
    "The Breaker": 1,
    "Molten Breastplate": 1,
    "Musket Ball": 250,
    "War Axe of the Night": 1,
    "Guide Voodoo Doll": 1,
    "Silver Bullet": 250,
    "Wizard Hat": 1,
    "Copper Chainmail": 1,
    "Jester's Arrow": 250,
    "Iron Axe": 1,
    "Molten Hamaxe": 1,
    "Sunfury": 1,
    "Copper Shortsword": 1,
    "Empty Bucket": 1,
    "Musket": 1,
    "Band of Starpower": 1,
    "Copper Pickaxe": 1,
    "Silver Chainmail": 1,
    "Flamelash": 1,
    "Harpoon": 1,
    "Vile Powder": 99,
    "Vilethorn": 1,
    "Molten Helmet": 1,
    "Hellfire Arrow": 250,
    "Trident": 1,
    "Wooden Hammer": 1,
    "Handgun": 1,
    "Flintlock Pistol": 1,
    "Shuriken": 250,
    "Light's Bane": 1,
    "Throwing Knife": 250,
    "Silver Hammer": 1,
    "Sandgun": 1,
    "Water Bolt": 1,
    "Flamarang": 1,
    "Blade of Grass": 1,
    "Meteor Shot": 250,
    "Goggles": 1,
    "Iron Broadsword": 1,
    "Spiky Ball": 250,
    "Lucky Horseshoe": 1,
    "Obsidian Skull": 1,
    "Meteor Suit": 1,
    "Gold Helmet": 1,
    "Shadow Helmet": 1,
    "Grenade": 20,
    "Magic Missile": 1,
    "Muramasa": 1,
    "Bottled Water": 30,
    "Blue Phaseblade": 1,
    "Wooden Bow": 1,
    "Shackle": 1,
    "Space Gun": 1,
    "Copper Broadsword": 1,
    "Fallen Star": 100,
    "Demon Scythe": 1,
    "Healing Potion": 30,
    "Blue Moon": 1,
    "Feral Claws": 1,
    "Copper Axe": 1,
}

